name: APP release
on: [workflow_dispatch]
        
jobs:
  APP:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2
          
      - name: Setup .NET Core SDK 6.0.404
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.404'

      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Build
        run: |
          cd App
          msbuild /t:SignAndroidPackage /t:PackageForAndroid /p:Configuration=Release /p:AndroidPackageFormat=apk
          cd bin/Release
          ls
    